name: Test and Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install root dependencies (if any)
      - name: Install root dependencies
        run: npm install

      # Install functions dependencies, including express
      - name: Install functions dependencies
        run: npm install --prefix functions

      # Build if you have a build step
      - name: Build (if applicable)
        run: npm run build --if-present

      # Run your tests
      - name: Run tests
        run: npm test

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Deploy Firebase Hosting and Functions
      - name: Deploy to Firebase
        run: firebase deploy --only hosting,functions --token "${{ secrets.FIREBASE_TOKEN }}"
